# Generated by Django 4.0.6 on 2022-09-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='count')),
                ('record', models.CharField(max_length=128, verbose_name='record')),
                ('reporter', models.CharField(max_length=128, verbose_name='reporter')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell', models.CharField(choices=[('internal', 'Internal'), ('system', 'System'), ('osquery', 'osquery')], default='system', max_length=8, verbose_name='shell')),
                ('line', models.CharField(help_text='Should avoid using commands that might need standard input.', max_length=512, verbose_name='command line')),
                ('data', models.TextField(blank=True, null=True, verbose_name='data')),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='success')),
                ('result', models.TextField(blank=True, null=True, verbose_name='result')),
                ('scheduled_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Executed now if left blank.', verbose_name='scheduled at')),
                ('delivered_at', models.DateTimeField(editable=False, null=True, verbose_name='delivered at')),
                ('acked_at', models.DateTimeField(editable=False, null=True, verbose_name='acked at')),
                ('handled_at', models.DateTimeField(editable=False, null=True, verbose_name='handled at')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('run_after', models.ManyToManyField(blank=True, help_text='Execute this command after running prior commands.', related_name='run_before', to='events.command', verbose_name='run after')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'command',
                'verbose_name_plural': 'commands',
                'get_latest_by': 'added_at',
            },
        ),
    ]
