# Generated by Django 4.1.1 on 2022-12-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_command_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='elapsed_time',
            field=models.FloatField(null=True, verbose_name='elapsed time'),
        ),
        migrations.AlterField(
            model_name='command',
            name='acked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acked at'),
        ),
        migrations.AlterField(
            model_name='command',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='handled at'),
        ),
        migrations.AlterField(
            model_name='command',
            name='requested_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
    ]
