# Generated by Django 4.2.9 on 2024-02-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_command_elapsed_time_alter_command_acked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='groupname',
            field=models.CharField(blank=True, default='alpacon', max_length=128, verbose_name='groupname'),
        ),
        migrations.AddField(
            model_name='command',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='username'),
        ),
    ]
