# Generated by Django 4.0.6 on 2022-08-15 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='key')),
                ('requested_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='requested IP')),
                ('requested_user_agent', models.CharField(default='', editable=False, max_length=256, verbose_name='requested user agent')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('sent_count', models.PositiveSmallIntegerField(default=0, verbose_name='sent count')),
                ('sent_at', models.DateTimeField(editable=False, null=True, verbose_name='sent at')),
                ('confirmed_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='confirmed IP')),
                ('confirmed_user_agent', models.CharField(default='', editable=False, max_length=256, verbose_name='confirmed user agent')),
                ('confirmed_at', models.DateTimeField(editable=False, null=True, verbose_name='confirmed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reset token',
                'verbose_name_plural': 'reset tokens',
            },
        ),
    ]
