# Generated by Django 4.0.5 on 2022-06-15 13:23

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='access key')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Limit the IP address to access API. Leave it empty to allow any IP address.', null=True, verbose_name='IP address')),
                ('concurrent', models.BooleanField(default=False, help_text='Enable this field to allow concurrent sessions for a client at a time.', verbose_name='concurrent sessions')),
                ('enabled', models.BooleanField(default=True, help_text='Enable this API client.', verbose_name='enabled')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token will be expired after this time.', null=True, validators=[api.validators.validate_future], verbose_name='expires at')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'API client',
                'verbose_name_plural': 'API clients',
                'abstract': False,
            },
        ),
    ]
