# Generated by Django 4.1.5 on 2023-01-10 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiclient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiclient',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
