# Generated by Django 4.1.1 on 2022-09-25 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128, verbose_name='name')),
                ('path', models.CharField(blank=True, default='', help_text='Specify the path to upload this file to. If this field is left blank, your home directory will be used as default.', max_length=512, verbose_name='path')),
                ('to_server', models.BooleanField(help_text='To upload, set this true. To download, set this false.', verbose_name='to server')),
                ('content', models.FileField(upload_to='websh/files/', verbose_name='content')),
                ('expires_at', models.DateTimeField(blank=True, verbose_name='expires at')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'file transfer',
                'verbose_name_plural': 'file transfers',
            },
        ),
    ]
