# Generated by Django 4.1.1 on 2022-10-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('websh', '0003_uploadedfile_delete_filetransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websh_sessions', related_query_name='websh_session', to='servers.server', verbose_name='server'),
        ),
    ]
