# Generated by Django 4.1.1 on 2022-12-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websh', '0005_session_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptychannel',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='websh.session', verbose_name='session'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='websh.session', verbose_name='session'),
        ),
    ]
