# Generated by Django 4.2.3 on 2023-07-24 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0007_alter_server_groups'),
        ('websh', '0006_ptychannel_session_userchannel_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128, verbose_name='name')),
                ('path', models.CharField(blank=True, default='', help_text='Specify the path for this file. If this field is left blank, your home directory will be used as default.', max_length=512, verbose_name='path')),
                ('content', models.FileField(upload_to='websh/files/', verbose_name='content')),
                ('expires_at', models.DateTimeField(blank=True, verbose_name='expires at')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'downloaded file',
                'verbose_name_plural': 'downloaded files',
            },
        ),
    ]
