# Generated by Django 4.2.3 on 2023-07-30 12:06

from django.core.serializers import serialize
from django.db import migrations


def backup_channels(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('websh', '0007_downloadedfile'),
    ]

    operations = [
        migrations.RunPython(backup_channels)
    ]
