# Generated by Django 4.2.3 on 2023-08-01 07:59

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('websh', '0008_backup_channel'),
    ]

    operations = [
        migrations.DeleteModel('PtyChannel'),
        migrations.DeleteModel('UserChannel'),
    ]

