# Generated by Django 4.2.3 on 2023-07-31 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websh', '0010_remove_session_pty_token_remove_session_user_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='pty_websocket_url',
        ),
        migrations.AddField(
            model_name='userchannel',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
