# Generated by Django 4.2.3 on 2023-08-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websh', '0012_restore_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptychannel',
            name='token_created_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='token created at'),
        ),
        migrations.AddField(
            model_name='ptychannel',
            name='token_expired_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='token expired at'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='is master'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='password',
            field=models.CharField(editable=False, max_length=16, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='read only'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='token_created_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='token created at'),
        ),
        migrations.AddField(
            model_name='userchannel',
            name='token_expired_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='token expired at'),
        ),
        migrations.AlterField(
            model_name='ptychannel',
            name='token',
            field=models.CharField(editable=False, max_length=32, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='userchannel',
            name='token',
            field=models.CharField(editable=False, max_length=32, null=True, verbose_name='token'),
        ),
    ]
