# Generated by Django 4.2.9 on 2024-02-21 10:26

import django.utils.timezone
from django.db import migrations, models


def update_session_user_and_group(apps, schema_editor):
    Session = apps.get_model('websh', 'Session')
    for instance in Session.objects.all():
        if instance.root:
            instance.username = 'root'
            instance.groupname = 'root'
        else:
            instance.username = instance.user.username
            instance.groupname = 'alpacon'
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_command_groupname_command_username'),
        ('websh', '0013_ptychannel_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.command', verbose_name='command'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='groupname',
            field=models.CharField(blank=True, default='alpacon', max_length=128, verbose_name='groupname'),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='session',
            name='groupname',
            field=models.CharField(blank=True, default='alpacon', max_length=128, verbose_name='groupname'),
        ),
        migrations.AddField(
            model_name='session',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.command', verbose_name='command'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='groupname',
            field=models.CharField(blank=True, default='alpacon', max_length=128, verbose_name='groupname'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='username',
            field=models.CharField(blank=True, max_length=128, verbose_name='username'),
        ),
        migrations.RunPython(update_session_user_and_group),
        migrations.RemoveField(
            model_name='Session',
            name='root'
        )
    ]
