# Generated by Django 4.0.6 on 2022-09-23 10:04

from django.db import migrations, models
import iam.models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', iam.models.MyUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='gid',
            field=models.PositiveIntegerField(blank=True, help_text='This GID will be used when creating a group on a server. This value should be unique. If this field is blank, we will automatically assign a unique value starting from 2000.', null=True, unique=True, verbose_name='GID'),
        ),
    ]
