# Generated by Django 4.1.1 on 2022-10-05 14:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_alter_group_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number should start with a country code (e.g., +00). We use this phone number to contact you for two-step verifications or various notifications.', max_length=128, region=None, verbose_name='phone number'),
        ),
    ]
