# Generated by Django 4.0.6 on 2022-09-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wsutils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('websocketclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wsutils.websocketclient')),
                ('name', models.SlugField(help_text='A name should only use letters, numbers, "_", and "-". No special characters or whitespaces allowed.', max_length=16, unique=True, verbose_name='name')),
                ('status', models.JSONField(null=True, verbose_name='status')),
                ('commissioned', models.BooleanField(default=False, verbose_name='commissioned')),
                ('version', models.CharField(blank=True, max_length=16, null=True, verbose_name='version')),
                ('osquery_version', models.CharField(blank=True, max_length=16, null=True)),
                ('started_at', models.DateTimeField(editable=False, null=True, verbose_name='started at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
            bases=('wsutils.websocketclient',),
        ),
    ]
