# Generated by Django 4.1.1 on 2022-11-14 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('hits', models.PositiveSmallIntegerField(default=0, verbose_name='hits')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added_at')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'installer',
                'verbose_name_plural': 'installers',
            },
        ),
    ]
