# Generated by Django 4.1.1 on 2022-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='load',
            field=models.FloatField(editable=False, null=True, verbose_name='load average (1m)'),
        ),
    ]
