# Generated by Django 4.1.1 on 2022-12-04 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0004_alter_server_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown is supported.', max_length=512, verbose_name='content')),
                ('private', models.BooleanField(default=False, help_text='Private notes are visible only to you.', verbose_name='private')),
                ('pinned', models.BooleanField(default=False, help_text='Pinned notes are listed first.', verbose_name='pinned')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
            },
        ),
    ]
