# Generated by Django 4.1.5 on 2023-03-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_user_phone'),
        ('servers', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(help_text='<ul><li>Select groups that are authorized to access this server.</li><li>If you select alpacon group, all registered users will have access.</li><li>This field cannot be blank.</li></ul>', to='iam.group', verbose_name='groups'),
        ),
    ]
