# Generated by Django 4.2 on 2023-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_user_phone'),
        ('servers', '0006_server_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(help_text='<ul><li>Select groups that are authorized to access this server.</li><li>If you select alpacon group, all registered users will have access.</li><li>This field cannot be blank.</li></ul>', related_name='servers', related_query_name='server', to='iam.group', verbose_name='groups'),
        ),
    ]
