# Generated by Django 4.0.6 on 2022-09-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC address')),
                ('type', models.PositiveIntegerField(verbose_name='type')),
                ('flags', models.PositiveIntegerField(verbose_name='flags')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'interface',
                'verbose_name_plural': 'interfaces',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'name', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('uid', models.BigIntegerField(verbose_name='UID')),
                ('gid', models.BigIntegerField(verbose_name='GID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('description', models.CharField(default='', max_length=64, verbose_name='description')),
                ('directory', models.CharField(default='', max_length=64, verbose_name='directory')),
                ('shell', models.CharField(default='', max_length=32, verbose_name='shell')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'system user',
                'verbose_name_plural': 'system users',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'uid', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('boot_time', models.DateTimeField(verbose_name='boot time')),
                ('timezone', models.CharField(max_length=16, verbose_name='local timezone')),
                ('uptime', models.PositiveBigIntegerField(verbose_name='uptime')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'system time',
                'verbose_name_plural': 'system times',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('source', models.CharField(max_length=64, verbose_name='source')),
                ('arch', models.CharField(blank=True, max_length=16, null=True, verbose_name='arch')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'system package',
                'verbose_name_plural': 'system packages',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'name', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('uuid', models.UUIDField(verbose_name='UUID')),
                ('cpu_type', models.CharField(default='', max_length=16, verbose_name='CPU type')),
                ('cpu_subtype', models.CharField(default='', max_length=32, verbose_name='CPU subtype')),
                ('cpu_brand', models.CharField(default='', max_length=64, verbose_name='CPU brand')),
                ('cpu_physical_cores', models.IntegerField(verbose_name='CPU physical cores')),
                ('cpu_logical_cores', models.IntegerField(verbose_name='CPU logical cores')),
                ('physical_memory', models.BigIntegerField(verbose_name='physical memory')),
                ('hardware_vendor', models.CharField(blank=True, default='', max_length=64, verbose_name='hardware vendor')),
                ('hardware_model', models.CharField(blank=True, default='', max_length=64, verbose_name='hardware model')),
                ('hardware_version', models.CharField(blank=True, default='', max_length=64, verbose_name='hardware version')),
                ('hardware_serial', models.CharField(blank=True, default='', max_length=64, verbose_name='hardware serial')),
                ('computer_name', models.CharField(blank=True, default='', max_length=64, verbose_name='computer name')),
                ('hostname', models.CharField(blank=True, default='', max_length=32, verbose_name='hostname')),
                ('local_hostname', models.CharField(blank=True, default='', max_length=64, verbose_name='local hostname')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'system information',
                'verbose_name_plural': 'system information',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('gid', models.BigIntegerField(verbose_name='GID')),
                ('groupname', models.CharField(max_length=32, verbose_name='groupname')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'system group',
                'verbose_name_plural': 'system groups',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'gid', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='PythonVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('python2', models.CharField(blank=True, max_length=32, null=True, verbose_name='python2')),
                ('python3', models.CharField(blank=True, max_length=32, null=True, verbose_name='python3')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'python version',
                'verbose_name_plural': 'python versions',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='PythonPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'python package',
                'verbose_name_plural': 'python packages',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'name', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='OsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('version', models.CharField(max_length=64, verbose_name='version')),
                ('major', models.SmallIntegerField(blank=True, null=True, verbose_name='major')),
                ('minor', models.SmallIntegerField(blank=True, null=True, verbose_name='minor')),
                ('patch', models.SmallIntegerField(blank=True, null=True, verbose_name='patch')),
                ('build', models.CharField(default='', max_length=16, verbose_name='build')),
                ('platform', models.CharField(max_length=16, verbose_name='platform')),
                ('platform_like', models.CharField(max_length=16, verbose_name='platform like')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'OS version',
                'verbose_name_plural': 'OS versions',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'added_at')},
            },
        ),
        migrations.CreateModel(
            name='InterfaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='address')),
                ('mask', models.GenericIPAddressField(verbose_name='mask')),
                ('broadcast', models.GenericIPAddressField(blank=True, null=True, verbose_name='broadcast')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proc.interface', verbose_name='interface')),
            ],
            options={
                'verbose_name': 'interface address',
                'verbose_name_plural': 'interface addresses',
                'unique_together': {('interface', 'address')},
            },
        ),
    ]
