# Generated by Django 4.0.6 on 2022-09-23 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_alter_user_managers_alter_group_gid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proc', '0002_alter_osversion_build_alter_systempackage_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemgroup',
            name='iam_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.group', verbose_name='IAM group'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proc.systemgroup', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='iam_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='IAM user'),
        ),
    ]
