# Generated by Django 4.0.6 on 2022-09-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0003_systemgroup_iam_group_systemuser_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel('SystemInfo'),
        migrations.DeleteModel('OsVersion'),
        migrations.DeleteModel('SystemTime'),
        migrations.DeleteModel('SystemUser'),
        migrations.DeleteModel('SystemGroup'),
        migrations.DeleteModel('Interface'),
        migrations.DeleteModel('InterfaceAddress'),
        migrations.DeleteModel('PythonVersion'),
        migrations.DeleteModel('SystemPackage'),
        migrations.DeleteModel('PythonPackage'),
    ]
