# Generated by Django 4.1.1 on 2022-10-14 09:52

from django.db import migrations, models
import uuid
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0006_alter_interfaceaddress_interface'),
    ]

    operations = [
        migrations.DeleteModel('InterfaceAddress'),
        migrations.CreateModel(
            name='InterfaceAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(verbose_name='address')),
                ('mask', models.GenericIPAddressField(verbose_name='mask')),
                ('broadcast', models.GenericIPAddressField(blank=True, null=True, verbose_name='broadcast')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='proc.interface', verbose_name='interface')),
            ],
            options={
                'verbose_name': 'interface address',
                'verbose_name_plural': 'interface addresses',
                'unique_together': {('interface', 'address')},
            },
        ),
    ]
