# Generated by Django 4.1.1 on 2022-11-22 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_installer'),
        ('proc', '0010_alter_osversion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadAverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True, verbose_name='is current')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('l1', models.FloatField(blank=True, default=0, verbose_name='1m avg load')),
                ('l5', models.FloatField(blank=True, default=0, verbose_name='5m avg load')),
                ('l15', models.FloatField(blank=True, default=0, verbose_name='15m avg load')),
                ('server', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='server')),
            ],
            options={
                'verbose_name': 'load average',
                'verbose_name_plural': 'load averrages',
                'get_latest_by': 'added_at',
                'abstract': False,
                'unique_together': {('server', 'added_at')},
            },
        ),
    ]
