# Generated by Django 4.1.1 on 2022-11-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0011_loadaverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadAverage',
        ),
    ]
