# Generated by Django 4.2.3 on 2023-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0013_alter_systemgroup_groupname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osversion',
            name='platform_like',
            field=models.CharField(blank=True, max_length=16, verbose_name='platform like'),
        ),
    ]
