# Generated by Django 4.2.3 on 2023-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0014_alter_osversion_platform_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonpackage',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='systempackage',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='systempackage',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='systempackage',
            name='version',
            field=models.CharField(max_length=128, verbose_name='version'),
        ),
    ]
