# Generated by Django 4.1.1 on 2022-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitoken', '0002_apitoken_remote_ip_apitoken_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name your token so that you can identify it easily.', max_length=128, verbose_name='name'),
        ),
    ]
