# Generated by Django 4.2.9 on 2024-03-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitoken', '0003_apitoken_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='apitoken',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'api')), fields=('name', 'user'), name='unique_api_token'),
        ),
    ]
