# Generated by Django 4.0.6 on 2022-09-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketClient',
            fields=[
                ('apiclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiclient.apiclient')),
            ],
            options={
                'verbose_name': 'WebSocket client',
                'verbose_name_plural': 'WebSocket clients',
            },
            bases=('apiclient.apiclient',),
        ),
        migrations.CreateModel(
            name='WebSocketSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(editable=False, null=True, verbose_name='deleted at')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='remote IP')),
                ('channel_id', models.CharField(editable=False, max_length=128, verbose_name='channel ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='wsutils.websocketclient', verbose_name='WebSocket client')),
            ],
            options={
                'verbose_name': 'WebSocket session',
                'verbose_name_plural': 'WebSocket sessions',
                'get_latest_by': 'added_at',
            },
        ),
    ]
