# Generated by Django 4.1.1 on 2022-09-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wsutils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', related_query_name='session', to='wsutils.websocketclient', verbose_name='WebSocket client'),
        ),
    ]
